### ISSUE TITLE
Trouble to install on weewx 5

### ISSUE THREAD

**Issue by jens-b** [morrowwm/weewxMQTT#4]
can't install it on weewx 5:
Extracting from zip archive weewxMQTT.zip
Traceback (most recent call last):
  File "/usr/share/weewx/weectl.py", line 74, in <module>
    main()
  File "/usr/share/weewx/weectl.py", line 66, in main
    namespace.func(namespace)
  File "/usr/share/weewx/weectllib/__init__.py", line 121, in dispatch
    namespace.action_func(config_dict, namespace)
  File "/usr/share/weewx/weectllib/extension_cmd.py", line 116, in install_extension
    ext.install_extension(namespace.source, no_confirm=namespace.yes)
  File "/usr/share/weewx/weecfg/extension.py", line 138, in install_extension
    extension_name = self._install_from_file(extension_path, filetype)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/extension.py", line 168, in _install_from_file
    extension_name = self.install_from_dir(extension_dir)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/extension.py", line 179, in install_from_dir
    installer_path, installer = weecfg.get_extension_installer(extension_dir)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/__init__.py", line 714, in get_extension_installer
    __import__('install')
  File "/tmp/tmpt73g4vp7/weewxMQTT-master/install.py", line 49
    files=[('bin/users/wxMesh'])]

**Comment by morrowwm** [comment]
I haven't tried weewx 5. I will spin up a test system...

Update: I've changed one line in wxMesh.py which seemed to be stopping my driver from starting. It's working OK now in my test system. Also updated the repository here.
```
diff weather/weewx/wxMesh.py_4 weather/weewx/wxMesh.py 
46c46
< DRIVER_VERSION = "0.2"
---
> DRIVER_VERSION = "0.3"
60c60
<     return wxMesh(**config_dict['wxMesh'])
---
>     return wxMesh(**config_dict[DRIVER_NAME])
87c87
<       self.client = mqtt.Client(client_id=self.client_id, protocol=mqtt.MQTTv31)
---
>       self.client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION1, client_id=self.client_id, protocol=mqtt.MQTTv31)
```
I set up the test system for this with the "pip" install method. Also had to add to install paho-mqtt in the venv:
```
python3 -m pip install  paho-mqtt
```

**Comment by morrowwm** [comment]
Please close the issue if it works for you.

**Comment by jens-b** [comment]
Hello morrowwm, it doesn't work for me: 
Downloaded it with 
wget -O weewxMQTT.zip https://github.com/morrowwm/weewxMQTT/archive/refs/heads/master.zip

try to install with:
sudo weectl extension install weewxMQTT.zip
gaves me the same error: 
Traceback (most recent call last):
  File "/usr/share/weewx/weectl.py", line 74, in <module>
    main()
  File "/usr/share/weewx/weectl.py", line 66, in main
    namespace.func(namespace)
  File "/usr/share/weewx/weectllib/__init__.py", line 121, in dispatch
    namespace.action_func(config_dict, namespace)
  File "/usr/share/weewx/weectllib/extension_cmd.py", line 116, in install_extension
    ext.install_extension(namespace.source, no_confirm=namespace.yes)
  File "/usr/share/weewx/weecfg/extension.py", line 138, in install_extension
    extension_name = self._install_from_file(extension_path, filetype)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/extension.py", line 168, in _install_from_file
    extension_name = self.install_from_dir(extension_dir)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/extension.py", line 179, in install_from_dir
    installer_path, installer = weecfg.get_extension_installer(extension_dir)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/__init__.py", line 714, in get_extension_installer
    __import__('install')
  File "/tmp/tmp1ctg3n1w/weewxMQTT-master/install.py", line 49
    files=[('bin/users/wxMesh'])]

kind regards
jens

**Comment by morrowwm** [comment]
There was an obvious error in the install script. @jens-b, could you try again?

**Comment by flippyreaper** [comment]
Hello, I have same problem as jens-b

flippy@weewx-ubuntu ~> sudo weectl extension install weewxMQTT.zip
Using configuration file /etc/weewx/weewx.conf
Install extension 'weewxMQTT.zip' (y/n)? y
Extracting from zip archive weewxMQTT.zip
Traceback (most recent call last):
  File "/usr/share/weewx/weectl.py", line 74, in <module>
    main()
  File "/usr/share/weewx/weectl.py", line 66, in main
    namespace.func(namespace)
  File "/usr/share/weewx/weectllib/__init__.py", line 121, in dispatch
    namespace.action_func(config_dict, namespace)
  File "/usr/share/weewx/weectllib/extension_cmd.py", line 116, in install_extension
    ext.install_extension(namespace.source, no_confirm=namespace.yes)
  File "/usr/share/weewx/weecfg/extension.py", line 138, in install_extension
    extension_name = self._install_from_file(extension_path, filetype)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/extension.py", line 168, in _install_from_file
    extension_name = self.install_from_dir(extension_dir)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/extension.py", line 179, in install_from_dir
    installer_path, installer = weecfg.get_extension_installer(extension_dir)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/__init__.py", line 714, in get_extension_installer
    __import__('install')
  File "/tmp/tmp3jg50xll/weewxMQTT-master/install.py", line 49
    files=[('bin/users/wxMesh.py'])]
                                 ^
SyntaxError: closing parenthesis ']' does not match opening parenthesis '('

**Comment by morrowwm** [comment]
> Hello, I have same problem as jens-b
```
 line 49 files=[('bin/users/wxMesh.py'])] ^ SyntaxError: closing parenthesis ']' does not match opening parenthesis '('
```
Argh, sorry. I made a mistake with the fix. Could you please try again? Thank you for testing this.

**Comment by benwatson42** [comment]
Hi, still having the same issue as those above
`Traceback (most recent call last):
  File "/usr/share/weewx/weectl.py", line 75, in <module>
    main()
  File "/usr/share/weewx/weectl.py", line 67, in main
    namespace.func(namespace)
  File "/usr/share/weewx/weectllib/__init__.py", line 90, in dispatch
    namespace.action_func(config_dict, namespace)
  File "/usr/share/weewx/weectllib/extension_cmd.py", line 116, in install_extension
    ext.install_extension(namespace.source, no_confirm=namespace.yes)
  File "/usr/share/weewx/weecfg/extension.py", line 140, in install_extension
    extension_name = self._install_from_file(extension_path, filetype)
  File "/usr/share/weewx/weecfg/extension.py", line 170, in _install_from_file
    extension_name = self.install_from_dir(extension_dir)
  File "/usr/share/weewx/weecfg/extension.py", line 181, in install_from_dir
    installer_path, installer = weecfg.get_extension_installer(extension_dir)
  File "/usr/share/weewx/weecfg/__init__.py", line 715, in get_extension_installer
    __import__('install')
  File "/tmp/tmpwocla_hv/weewxMQTT-master/install.py", line 50
    )
    ^`

Any fix for this? Thanks!

**Comment by BliXem1** [comment]
+1:

`root@WeeWX:~# weectl extension install https://github.com/morrowwm/weewxMQTT/archive/master.zip
Using configuration file /etc/weewx/weewx.conf
Install extension 'https://github.com/morrowwm/weewxMQTT/archive/master.zip' (y/n)? y
Extracting from zip archive /tmp/tmpryqvua_4
Traceback (most recent call last):
  File "/usr/share/weewx/weectl.py", line 75, in <module>
    main()
  File "/usr/share/weewx/weectl.py", line 67, in main
    namespace.func(namespace)
  File "/usr/share/weewx/weectllib/__init__.py", line 90, in dispatch
    namespace.action_func(config_dict, namespace)
  File "/usr/share/weewx/weectllib/extension_cmd.py", line 116, in install_extension
    ext.install_extension(namespace.source, no_confirm=namespace.yes)
  File "/usr/share/weewx/weecfg/extension.py", line 130, in install_extension
    extension_name = self._install_from_file(test_fd.name, filetype)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/extension.py", line 170, in _install_from_file
    extension_name = self.install_from_dir(extension_dir)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/extension.py", line 181, in install_from_dir
    installer_path, installer = weecfg.get_extension_installer(extension_dir)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/__init__.py", line 715, in get_extension_installer
    __import__('install')
  File "/tmp/tmpuxzgt0p4/weewxMQTT-master/install.py", line 50
    )
    ^
SyntaxError: closing parenthesis ')' does not match opening parenthesis '{' on line 26
`

**Comment by morrowwm** [comment]
I somehow still had a missing "}" in the initialization. Could you test again?

**Comment by benwatson42** [comment]
different error for me now:

`Traceback (most recent call last):
  File "/usr/share/weewx/weectl.py", line 75, in <module>
    main()
  File "/usr/share/weewx/weectl.py", line 67, in main
    namespace.func(namespace)
  File "/usr/share/weewx/weectllib/__init__.py", line 90, in dispatch
    namespace.action_func(config_dict, namespace)
  File "/usr/share/weewx/weectllib/extension_cmd.py", line 116, in install_extension
    ext.install_extension(namespace.source, no_confirm=namespace.yes)
  File "/usr/share/weewx/weecfg/extension.py", line 140, in install_extension
    extension_name = self._install_from_file(extension_path, filetype)
  File "/usr/share/weewx/weecfg/extension.py", line 170, in _install_from_file
    extension_name = self.install_from_dir(extension_dir)
  File "/usr/share/weewx/weecfg/extension.py", line 181, in install_from_dir
    installer_path, installer = weecfg.get_extension_installer(extension_dir)
  File "/usr/share/weewx/weecfg/__init__.py", line 715, in get_extension_installer
    __import__('install')
  File "/tmp/tmpt_plq6vl/weewxMQTT-master/install.py", line 28
    driver = user.wxMesh
    ^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?`


if it helps you out, I'm on ubuntu 22 and weewx 5.1.0

**Comment by morrowwm** [comment]
It looks like the installer has changed substantially since I wrote this extension. I'll have to learn how it works now.

In the meantime, you should be OK to just copy wxMesh.py into ./bin/user, wherever that is in your baseline installation. And then add configuration into weewx.conf

**Comment by morrowwm** [comment]
Also, I'd recommend having a look at https://github.com/bellrichm/WeeWX-MQTTSubscribe. It's more active, and a more feature rich MQTT interface.

**Comment by BliXem1** [comment]
I'm gonna try that. I know of WeeWX-MQTTSubscribe but your extension seems easier, thats why I want to try it :)

**Comment by morrowwm** [comment]
Mine is definitely easier. I don’t actively maintain it though.





On Sunday, August 24, 2025, 03:36, BliXem1 ***@***.***> wrote:

BliXem1 left a comment (morrowwm/weewxMQTT#4)
I'm gonna try that. I know of WeeWX-MQTTSubscribe but your extension seems easier, thats why I want to try it :)

**Comment by BliXem1** [comment]
OK, only this is needed to make it work?

_In the meantime, you should be OK to just copy wxMesh.py into ./bin/user, wherever that is in your baseline installation. And then add configuration into weewx.conf_

Any idea where I need to copy it within Debian?
Indeed, your extension seems way much easier. I hope I can make it work though.

**Comment by benwatson42** [comment]
> Any idea where I need to copy it within Debian? Indeed, your extension seems way much easier. I hope I can make it work though.

https://weewx.com/docs/5.1/usersguide/where/
the bin/user directory is inside the WEEWX_ROOT, which on debian is /etc/weewx/

**Comment by benwatson42** [comment]
Thanks @morrowwm , appreciate your quick replies even though you aren't actively developing any more. I'll try both these suggestions. 
Cheers!

**Comment by morrowwm** [comment]
I run weewx on debian also, and my wxMesh.py file is at `/etc/weewx/bin/user/wxMesh.py`.

Let me know if you need help on the weewx.conf content. It should be straightforward. I have:
```
station_type = wxMesh   
...   
   
[wxMesh]
    driver = user.wxMesh
    
    # MQTT specifics
    host = XXXXX    # MQTT broker hostname
    # set mosquitto client, username and password using e.g. mosquitto_passwd /etc/mosquitto/mosquitto.pwd orca
    # don't forget to restart mosquitto
    client = orca
    username = weewx_user
    password = bigF1n!
    topic = "wx/#"    # topic is all weather (indoor and outdoor, e.g.) Sensors publish to this topic
    
    poll_interval = 10
    
    [[label_map]]
        TIME = dateTime
        HUMT = outTemp
        HUM  = outHumidity
        INTE = inTemp
        INHU = inHumidity
        PRES = barometer
        IRRA = radiation
        PVV  = supplyVoltage
        BATV = consBatteryVoltage
        TEMP = extraTemp1
        SYST = extraTemp2
        WDIR = windDir
        WIND = windSpeed
# INBP = barometer
```
